//! [`axum`] based Scanner API router.
use axum::{
    Router,
    body::Body,
    extract::{DefaultBodyLimit, State},
    http::{Request, Response},
    middleware::{self, Next},
    routing::{get, head},
};
use tower::limit::ConcurrencyLimitLayer;

use crate::api::states::Feed;

use super::{auth::Authentication, routes::*};
use scannerlib::models::FeedState;

use super::ApiConfig;

/// Injects default headers to all responses.
///
/// This middleware adds three default headers to *every* HTTP response. This includes the 401 unauthorized
/// responses generated by the [`AuthService`](super::auth::AuthService) on failed authentications and
/// 404 not found for unregistered routes.
async fn default_headers(
    State((authentication, feed)): State<(Authentication, Feed)>,
    request: Request<Body>,
    next: Next,
) -> Response<Body> {
    let mut response = next.run(request).await;

    let headers = response.headers_mut();
    headers.insert(
        "api-version",
        crate::api::API_VERSION
            .parse()
            .expect("valid HTTP header value"),
    );

    // Authentication is the currently enabled authentication method
    headers.insert(
        "authentication",
        authentication
            .to_string()
            .parse()
            .unwrap_or_else(|_| panic!("'{}' is not a valid header value", authentication)),
    );

    let feed_state_str = match &*feed.state() {
        FeedState::Unknown | FeedState::Syncing => "unavailable".to_string(),
        FeedState::Synced(vt, adv) => format!("{vt}{adv}"),
    };
    headers.insert(
        "feed-version",
        feed_state_str.parse().expect("valid HTTP header value"),
    );

    response
}

/// Creates the api router.
///
/// This is the main entry point for most axum functionalities, configuring all routes,
/// authentication, shared states and more based on the given [`ApiConfig`].
///
/// All routes with the `/scans` and `/container-image-scanner` prefix require authorization via either
/// mtls or api keys, with the former being preferred. The actual verification of the client certificates
/// is handled by [`MtlsAcceptor`](super::mtls::MtlsAcceptor) which, if a certificate is valid,
/// injects it's sh256 hash into the extensions of the [`Request`].
///
/// Unless specified otherwise the `HEAD` routes are auto generated by [`axum`] from their `GET` counterpart.
///
/// | Method   | Route                                             | Authenticated |
/// |----------|---------------------------------------------------|---------------|
/// | `HEAD`   | /health                                           |               |
/// | `GET`    | /health/alive                                     |               |
/// | `GET`    | /health/ready                                     |               |
/// | `GET`    | /health/started                                   |               |
/// | `HEAD`   | /scans                                            | ✓             |
/// | `GET`    | /scans*                                           | ✓             |
/// | `POST`   | /scans                                            | ✓             |
/// | `GET`    | /scans/preferences                                | ✓             |
/// | `GET`    | /scans/{id}                                       | ✓             |
/// | `POST`   | /scans/{id}                                       | ✓             |
/// | `DELETE` | /scans/{id}                                       | ✓             |
/// | `GET`    | /scans/{id}/results                               | ✓             |
/// | `GET`    | /scans/{id}/results/{rid}                         | ✓             |
/// | `GET`    | /scans/{id}/status                                | ✓             |
/// | `HEAD`   | /container-image-scanner/scans                    | ✓             |
/// | `GET`    | /container-image-scanner/scans*                   | ✓             |
/// | `POST`   | /container-image-scanner/scans                    | ✓             |
/// | `GET`    | /container-image-scanner/scans/preferences        | ✓             |
/// | `GET`    | /container-image-scanner/scans/{id}               | ✓             |
/// | `POST`   | /container-image-scanner/scans/{id}               | ✓             |
/// | `DELETE` | /container-image-scanner/scans/{id}               | ✓             |
/// | `GET`    | /container-image-scanner/scans/{id}/results       | ✓             |
/// | `GET`    | /container-image-scanner/scans/{id}/results/{rid} | ✓             |
/// | `GET`    | /container-image-scanner/scans/{id}/status        | ✓             |
/// | `HEAD`   | /vts                                              |               |
/// | `GET`    | /vts                                              |               |
/// | `HEAD`   | /notus                                            |               |
/// | `GET`    | /notus                                            |               |
/// | `POST`   | /notus/{os}                                       |               |
///
/// \*: Only present if the `enable-get-scans` option is set to true. Default: true.
pub fn create_router(cfg: &ApiConfig) -> Router {
    Router::new()
        .nest(
            // All health routes are currently NOPs
            "/health",
            Router::new()
                .route("/", head(()))
                .route("/alive", get(()))
                .route("/ready", get(()))
                .route("/started", get(())),
        )
        .nest(
            "/scans",
            scans::router(
                cfg.scanner.clone(),
                cfg.auth_method,
                cfg.api_keys.clone(),
                cfg.enable_additional_routes,
            ),
        )
        .nest("/vts", vts::router(cfg.feed.clone()))
        .nest("/notus", notus::router(cfg.notus.clone()))
        .nest(
            "/container-image-scanner/scans",
            container_image_scanner::router(
                cfg.image_scanner.clone(),
                cfg.auth_method,
                cfg.api_keys.clone(),
                cfg.enable_additional_routes,
            ),
        )
        // Inject the api-version, feed-version and authentication headers into all responses
        .layer(middleware::from_fn_with_state(
            (cfg.auth_method, cfg.feed.clone()),
            default_headers,
        ))
        // Limit of concurrent requests
        .layer(ConcurrencyLimitLayer::new(cfg.max_requests))
        // Set the body payload limit to 32MiB (forms, json, etc).
        // The default is 2MB
        .layer(DefaultBodyLimit::max(32 * 1024 * 1024))
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use crate::{
        Config,
        api::{ApiConfig, tests::send_request},
    };
    use axum::{
        body::Body,
        http::{HeaderValue, Request, StatusCode},
    };

    async fn config() -> anyhow::Result<ApiConfig> {
        let cfg = Config::from_file(
            Path::new(env!("CARGO_MANIFEST_DIR")).join("data/tests/scanner/config/basic.toml"),
        );
        crate::init_api(cfg).await
    }

    /// Tests whether the three default headers are added to responses
    #[tokio::test]
    async fn default_headers() -> anyhow::Result<()> {
        let cfg = config().await?;
        let mut router = super::create_router(&cfg).into_service();

        let req = Request::head("/health").body(Body::empty())?;
        let resp = send_request(&mut router, req).await;
        assert_eq!(resp.status(), StatusCode::OK);

        let headers = resp.headers();
        assert_eq!(
            headers.get("api-version"),
            Some(&HeaderValue::from_str(crate::api::API_VERSION)?)
        );
        assert_eq!(
            headers.get("authentication"),
            Some(&HeaderValue::from_str("disabled")?)
        );
        assert_eq!(
            headers.get("feed-version"),
            Some(&HeaderValue::from_str("unavailable")?)
        );

        Ok(())
    }
}
