#!/bin/sh
#
# Some systems have their librairies named <name>.so.0.0.0 and
# <name>.so.0 and some other systems have their librairies called
# <name>.so.0.0. We just pick the right one...
#
if [ -f .libs/lib$1.so.0 ];then
cp .libs/lib$1.so.0 $1.nes
else
if [ -f .libs/lib$1.so.0.0 ];then
cp .libs/lib$1.so.0.0 $1.nes
else
if [ -f .libs/lib$1.so.1.0 ];then
cp .libs/lib$1.so.1.0 $1.nes
else if [ -f .libs/lib$1.sl.0.0 ]; then		# HP/UX
cp .libs/lib$1.sl.0.0 $1.nes
else
if [ -f .libs/$1.so.0.0.0 ];then		# Digital UNIX
cp .libs/lib$1.so.0.0.0 $1.nes
else
if [ -f .libs/lib$1.0.0.0.dylib ]; then 		# Darwin
cp .libs/lib$1.0.0.0.dylib $1.nes
fi
fi
fi
fi
fi
fi
