name: "Setup Rust Environment"
description: "Install dependencies, set up the pinned Rust toolchain, and restore build caches"
inputs:
  cache-key:
    description: "Distinguishes build artifacts produced by different Cargo commands"
    required: true
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/cache-rust
      with:
        cache-key: ${{ inputs.cache-key }}
    - run: sudo apt update || true
      shell: bash
    - run: sudo apt-get install -y libpcap-dev libclang-dev libsnmp-dev patchelf 
      shell: bash
    - run: sudo apt-get install -y capnproto # required for sequoia-ipc
      shell: bash
    - name: Install pinned Rust toolchain
      run: rustup toolchain install
      working-directory: rust
      shell: bash
