.TH OPENVASD-CONFIG 1 "October 2008" "The OpenVAS Project" "User Manuals"
.SH NAME
openvasd-config \- displays compiler/linker flags for the OpenVAS server
.SH SYNOPSIS
.B openvasd-config
.I <[--cflags] [--ldflags] [--libs]>
.SH DESCRIPTION
.BR openvasd-config
script displays the compiler/linker flags other program sources
can use to link to the OpenVAS server.
.SH OPTIONS
.TP
.B \-\-cflags
Show $(CFLAGS) variable.
.TP
.B \-\-libs
Show $(LIBS) variable.
.TP
.B \-\-version
Show the version of the OpenVAS server.
.SH SEE ALSO
.BR openvasd (8).
.SH AUTHOR
Renaud Deraison <deraison@nessus.org>.
.sp
This manual page was written by Tim Brown <timb@nth-dimension.org.uk>.
