.TH OpenVAS-MKCERT 8 "January 2011" "The OpenVAS Project" "User Manuals"
.SH NAME
openvas-mkcert \- Creates a scanner certificate
.sp
.SH SYNOPSIS
.B openvas-mkcert
.RB [ -q ]
.RB [ -f ]

.SH DESCRIPTION

The 
.B OpenVAS Scanner
protects its communication with clients by using SSL. SSL
requires the scanner to present a certificate to the client, and the client can
optionally present a certificate to the scanner.

This script
.B openvas-mkcert
creates a certificate authority (if none exists already) and generates the
scanner certificate.

.SH OPTIONS

.I -q
quickly generates a new certificate, without asking any question

.I -f
force overwriting of already existing certificate files


.SH SEE ALSO

.BR openvassd (8),\  openvas-mkcert-client (1),\  openssl(1)

.SH MORE INFORMATION ABOUT THE OpenVAS PROJECT
The canonical places where you will find more information 
about the OpenVAS project are: 
.RS
.UR
http://www.openvas.org/
.UE
(Official site)
.br

.SH AUTHOR

.B openvas-mkcert
was derived from nessus-mkcert which is was written by Michel
Arboi <arboi@alussinan.org> and Renaud Deraison <deraison@cvs.nessus.org>
