.TH OpenVAS-MKCERT 8 "September 2001" "The OpenVAS Project" "User Manuals"
.SH NAME
openvas-mkcert \- Creates a server certificate
.sp
.SH SYNOPSIS
.BI openvas-mkcert  
[ -q ]

.SH DESCRIPTION

The 
.B OpenVAS Security Scanner
protects the communication between the client and the server by using SSL. SSL
requires the server to present a certificate to the client, and the client can
optionally present a certificate to the server.

This script
.B openvas-mkcert
creates a certificate authority (if none exists already) and generates the
server certificate.

.SH OPTIONS

.I -q
quickly generates a new certificate, without asking any question


.SH SEE ALSO

.BR openvasd (8),\  openvas-mkcert-client (1),\  openssl(1)

.SH MORE INFORMATION ABOUT THE NESSUS PROJECT
The canonical places where you will find more information 
about the OpenVAS project are: 
.RS
.UR
http://www.openvas.org/
.UE
(Official site)
.br
.UR
http://cvs.openvas.org/
.UE
(Developers site)
.RE

.SH AUTHOR

.B openvas-mkcert
was written by Michel Arboi <arboi@alussinan.org> and Renaud
Deraison <deraison@cvs.nessus.org>
