#!/bin/bash
owner=${1:-greenbone}
if [ -d "/workspaces/$owner" ]; then
    target_dir="/workspaces/$owner/openvas-scanner"
else
    target_dir="/workspaces/openvas-scanner"
fi

/usr/local/bin/build-cmake-project.sh "$target_dir"