.TH OpenVAS-RMUSER 8 "February 2001" "The OpenVAS Project" "User Manuals"
.SH NAME
openvas-rmuser \- removes a user from the openvassd userbase
.sp
.SH SYNOPSIS
.BI openvas-rmuser\ [\| <login> \|]

.SH DESCRIPTION

The 
.B OpenVAS Security Scanner
comes with its own user base which contains the list of who can
use the services of 
.BR openvasad ,
and what restriction (or
.IR rules ) 
each user has.


.BI openvas-rmuser
is a simple program which will remove user from the proper openvasad
configuration files, as well as its data (saved KBs and saved sessions).

.SH SEE ALSO

.BR openvas-adduser (8),\  openvassd (8),\  openvas (1)

.SH MORE INFORMATION ABOUT THE OPENVAS PROJECT
The canonical places where you will find more information 
about the OpenVAS project are: 

.RS
.UR
http://www.openvas.org/
.UE
(Official site)
.br
.UR
http://cvs.openvas.org/
.UE
(Developers site)
.RE
   

.SH AUTHOR

.B openvas-rmuser 
was quickly written by Renaud Deraison <deraison@cvs.nessus.org>

