name: Labeler

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: read

jobs:
  label:
    runs-on: self-hosted-generic
    steps:
        - uses: greenbone/actions/pr-conventional-commit-labeler@main
          with:
            configuration-toml: release_tag.toml

