name: "Documentation"

on:
  workflow_call:
  pull_request:
    paths:
      - "**/*.md"
      - ".github/workflows/docs.yml"

jobs:
  Markdown-Links:
    runs-on: ubuntu-latest
    steps:
      - name: Check out openvas-scanner
        uses: actions/checkout@v7
      - name: Install lychee
        run: sudo snap install lychee
      - name: Check Markdown links
        run: ./check.sh --verbose lychee
