name: functional

on: [workflow_call]

jobs:
  # Tests that gvm-libs, openvas-smb and openvas dependencies work together and
  # that openvas is buildable and integrates openvas-smb when available
  distributed-monolith-railguard:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        system:
          - debian_stable
          - debian_bookworm
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/copy-docker-binaries
        with:
          arch: amd64 
      - run: ./check.sh --verbose ci-railguard
        env:
          RAILGUARD_SYSTEM: ${{ matrix.system }}
