name: "Linting"

on: [workflow_call]

jobs:
  C:
    runs-on: ubuntu-latest
    steps:
      - name: Check out openvas-scanner
        uses: actions/checkout@v6
      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
      - name: Formatting
        run: ./check.sh --verbose lint-c
  Rust:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-rust
      - run: ../check.sh --verbose lint-rust
  Rust-Typos:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-rust
      - run: cargo install typos-cli || true
      - run: ../check.sh --verbose typos
  License-Headers:
    runs-on: ubuntu-latest
    steps:
      - name: Check out openvas-scanner
        uses: actions/checkout@v6
      - name: Check license headers
        run: ./check.sh --verbose license-headers
