[package]
name = "rpmdb"
version = "0.1.0"
edition = "2024"
authors = [
    "yybit <yybit2@gmail.com>",
]
license = "MIT"
# probably should change to ours as we forked that
homepage = "https://github.com/yybit/rpmdb-rs"
repository = "https://github.com/yybit/rpmdb-rs"
description = "Rust implementation of rpmdb"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1"
byteorder = "1"
rusqlite = "0"

serde = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
